### ISSUE TITLE
Date of Birth Range

### ISSUE THREAD

**Issue by a-machado-ipsg** [INTERPOL-Innovation-Centre/ANSI-NIST-XML-ITL-Implementation#15]
The field 2/DBR [02.036] Date of Birth Range should define the limits of the range (from ddmmyyyy to ddmmyyyy)

**Comment by Jeremy-M-Int** [comment]
Date of Birth Range (DBR) does indeed define start and end dates as in the example given below:

`<int-i:PersonBirthDateRange>
<nc:StartDate>
<nc:Date>1948-01-01</nc:Date>
</nc:StartDate>
<nc:EndDate>
<nc:Date>1960-12-31</nc:Date>
</nc:EndDate>
</int-i:PersonBirthDateRange>`
