### ISSUE TITLE
Reconsider / Confirm - QS | QUICK SEARCH Result Determination Code

### ISSUE THREAD

**Issue by Jeremy-M-Int** [INTERPOL-Innovation-Centre/ANSI-NIST-XML-ITL-Implementation#2]
It would not seem that QS | QUICK SEARCH is any different from the UC | UNCONFIRMED or even needed.

QS | QUICK SEARCH = Requests a set of possible matches with one or more candidates. Appropriate match confidence rating (separate field) where results potentially to be used without further verification activity anticipated.

**Comment by epcondon** [comment]
Quick Search has a response confidence/score and is not limited to a single response.

**Comment by Jeremy-M-Int** [comment]
Discussed and clarified with INSIWG:

- UNCONFIRMED => returning a certain max number of candidates (above the low threshold) anticipated for verification by an expert in the requesting country/office
- QUICK SEARCH => returning candidates above a "medium" threshold accepting a trade-off between FAR/FRR without any verification by an expert in the requesting country/office

DECISION: Keeping both values to distinguish between the 2 use cases (and intentions from the requesting country/office)
